pool:
  name: Azure Pipelines
  demands:
  - xcode
  - JDK

steps:


- task: aloisdeniel.flutter.flutter-install.FlutterInstall@0
  displayName: 'Flutter Install'

- task: aloisdeniel.flutter.flutter-build.FlutterBuild@0
  displayName: 'Flutter Build apk'
  inputs:
    debugMode: true

- task: AndroidSigning@3
  displayName: 'Signing and aligning APK file(s) **/*.apk'
  inputs:
    apksignerKeystoreFile: appKey.jks
    apksignerKeystorePassword: 123456
    apksignerKeystoreAlias: key
    zipalign: false

- task: CopyFiles@2
  displayName: 'Copy Build Files'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: |
     **/apk/debug/*debug*.apk
     **/apk/release/*release*.apk
    TargetFolder: '$(build.artifactstagingdirectory)'


